GET http://localhost:8080/Kiah/webapi/person/all

###
POST http://localhost:8080/Kiah/webapi/person/
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{
  "fname": "frederik",
  "lname": "hess",
  "phone": "13371377"
}

###
PUT http://localhost:8080/Kiah/webapi/person/
Content-Type: application/json

{"id": "2","name": "daniell", "age": 1}

###
PUT http://localhost:8080/Kiah/webapi/person/2
Content-Type: application/json

{"name": "daniel", "age": 12}
